-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5da199bb8d60f764c0f77a20b0a1dc3a7640bcdd
    hooks:
    -   id: flake8
        language_version: python3
        args:
        - --ignore=E501,F401,E712,W503
        exclude: setup.py
    -   id: check-yaml
        language_version: python3
    -   id: end-of-file-fixer
        language_version: python3
    -   id: trailing-whitespace
        language_version: python3
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.6.4
    hooks:
    -   id: pylint
        language_version: python3
        args:
        - --rcfile=.pylintrc
        exclude: setup.py
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: 149e61b7a717945143fe51f010fe1c576e729a9f
    hooks:
    -   id: pep257
        language_version: python3
        args:
        - --ignore=D301,D203
        exclude: setup.py
